#  Numpy 基础

## 生成Numpy 数组

###  从已有的数据中创建数组

In [3]:
import numpy as np

lst1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(lst1)
print(nd1)
print(type(nd1))

[3.14 2.17 0.   1.   2.  ]
<class 'numpy.ndarray'>


In [21]:
import numpy as np

lst2 = [[3.14, 2.17, 0, 1, 2],[1,2,3,4,5]]
nd2 = np.array(lst2)
print(nd2)
print(type(nd2))

[[3.14 2.17 0.   1.   2.  ]
 [1.   2.   3.   4.   5.  ]]
<class 'numpy.ndarray'>


###  利用 random 模块生成数组

<img src="https://raw.githubusercontent.com/Xpccccc/PicGo/main/data202405161114575.png">

In [10]:
import numpy as np

nd3 = np.random.random([3,3])
print(nd3)
print("nd3的形状为：",nd3.shape)

[[0.10702201 0.55215444 0.44866425]
 [0.60830197 0.08425423 0.30047564]
 [0.64181151 0.5743229  0.85278865]]
nd3的形状为： (3, 3)


In [49]:
import numpy as np

np.random.seed(123)
nd4 = np.random.randn(2,3)
print(nd4)


np.random.shuffle(nd4)
print("随机打乱后的数据：")
print(nd4)
print(type(nd4))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
随机打乱后的数据：
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]
<class 'numpy.ndarray'>


###  创建特定形状的多维数组

In [48]:
import numpy as np
# 生成全是 0 的 3x3 矩阵
nd5 = np.zeros((3,3))
print(nd5)
# 生成和nd5形状一样的全1矩阵
# np.ones_like(nd5)
nd6 = np.ones([3,3])
print(nd6)
# 生成 3 阶的单位矩阵
nd7 = np.eye(3)
print(nd7)
# 生成 3 阶对角矩阵
nd8 = np.diag([1,2,3])
print(nd8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [59]:
# 把生成的数据保存下来
import numpy as np

nd9 = np.random.random([5,5])
np.savetxt(X=nd9, fname='./test1.txt')
nd10 = np.loadtxt('./test1.txt')
print(nd10)

[[0.04093414 0.30051671 0.40939041 0.37251939 0.33997017]
 [0.81257008 0.52820553 0.55382711 0.11720684 0.78460482]
 [0.43458619 0.07722273 0.18181153 0.52101088 0.47933417]
 [0.31354249 0.09966921 0.59655266 0.24816989 0.60434016]
 [0.30511365 0.89730494 0.58201533 0.71249243 0.68361547]]


###  利用 arrange、linspace 函数生成数组

In [6]:
import numpy as np

print(np.arange(10))
print(np.arange(0,10))
print(np.arange(1,4,0.5))
print(np.arange(9,-1,-1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


In [16]:
import numpy as np

print(np.linspace(0,1,10))
print(np.logspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


## 获取元素

In [35]:
import numpy as np

np.random.seed(2024)
nd11 = np.random.random([10])
print(nd11)
# 获取第4个位置的元素
nd11[3]
# 截取一段数据
nd11[3:6] # 范围[1,6)
# 截取固定间隔数据
nd11[1:6:2] # 范围[1,6) 间隔为2
# 倒序取数
nd11[::-2] # 范围[0,10) 间隔为2 ，反过来
# 截取一个多维数组的一个区域内的数据
nd12 = np.arange(25).reshape([5,5])
print(nd12)
nd12[1:3,1:3]
# 截取多维数组中，数值在一个值域内的的数据
nd12[(nd12>3)&(nd12<10)]
# 截取多维数组中，指定的行，如读取第2，3行
nd12[[1,2]] # 或nd12[1:3,:]
# 截取多维数组中，指定的列，如读取第2，3列
nd12[:,1:3] # 这个前面的:不能省略

[0.58801452 0.69910875 0.18815196 0.04380856 0.20501895 0.10606287
 0.72724014 0.67940052 0.4738457  0.44829582]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [42]:
import numpy as np
from numpy import random as nr

a = np.arange(1,25,dtype=float)
c1 = nr.choice(a,size=(3,4)) # size指定输出形状
c2 = nr.choice(a,size=(3,4),replace=False) # replece缺省为True，即可重复抽取
# 下式中参数p指定每个元素对应的抽取概率，缺省为每个元素被抽取的概率相同
c3 = nr.choice(a,size=(3,4),p=a/np.sum(a))
print("随机可重复抽取")
print(c1)
print("随机但不可重复抽取")
print(c2)
print("随机但按指定概率抽取")
print(c3)

随机可重复抽取
[[24. 19. 23.  7.]
 [24. 18. 14. 21.]
 [ 6.  1. 14. 19.]]
随机但不可重复抽取
[[ 6. 17.  5. 24.]
 [13. 14. 16. 12.]
 [23. 15. 21.  2.]]
随机但按指定概率抽取
[[12. 24. 13. 16.]
 [14. 24. 12. 10.]
 [17. 23. 23. 11.]]


## Numpy 的算数运算

### 对应元素相乘

In [54]:
import numpy as np

A = np.array([[1,2],[-1,4]])
B = np.array([[2,0],[3,4]])
A*B
np.multiply(A,B)
print(A*2.0)
print(A/2.0)


X = np.random.rand(2,3)
def softmoid(x):
    return 1/(1+np.exp(-x))
def relu(x):
    return np.maximum(0,x);
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

print("输出参数X的形状：",X.shape)
print("输出激活函数softmoid的形状：",softmoid(X).shape)
print("输出激活函数relu的形状：",relu(X).shape)
print("输出激活函数softmax的形状：",softmax(X).shape)

[[ 2.  4.]
 [-2.  8.]]
[[ 0.5  1. ]
 [-0.5  2. ]]
输出参数X的形状： (2, 3)
输出激活函数softmoid的形状： (2, 3)
输出激活函数relu的形状： (2, 3)
输出激活函数softmax的形状： (2, 3)


### 点积运算

In [56]:
import numpy as np

X1 = np.array([[1,2],[3,4]])
X2 = np.array([[5,6,7],[8,9,10]])
X3 = np.dot(X1,X2)
print(X3)

[[21 24 27]
 [47 54 61]]


## 数组变形

### 更改数组的形状

In [63]:
# 1.reshape

import numpy as np

arr = np.arange(10)
print(arr)
# 将向量 arr 的维度变为2行5列
print(arr.reshape(2,5))
# 指定维度时可以只指定行数或者列数，其他用 -1 代替
print(arr.reshape(5,-1))
print(arr.reshape(-1,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [66]:
# 2.resize

import numpy as np

arr = np.arange(10)
print(arr)
# 将向量 arr 的维度变为2行5列
arr.resize(2,5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
# 3.T

import numpy as np
arr = np.arange(12).reshape(3,4)
# 向量 arr 为3行4列
print(arr)
# 将向量 arr 进行转置为4行3列
print(arr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [74]:
# 4.ravel

import numpy as np

arr = np.arange(6).reshape(2,-1)
print(arr)
# 按照列优先，展平
print("按照列优先，展平")
print(arr.ravel('F'))
# 按照行优先，展平
print("按照行优先，展平")
print(arr.ravel())

[[0 1 2]
 [3 4 5]]
按照列优先，展平
[0 3 1 4 2 5]
按照行优先，展平
[0 1 2 3 4 5]


In [83]:
# 5.flatten

import numpy as np

a = numpy.floor(10*np.random.random((3,4)))
print(a)
# 按照列优先，展平
print("按照列优先，展平")
print(a.flatten('F'))
# 按照行优先，展平
print("按照行优先，展平")
print(a.flatten())

[[4. 5. 5. 3.]
 [9. 6. 3. 5.]
 [4. 2. 2. 5.]]
按照列优先，展平
[4. 9. 4. 5. 6. 2. 5. 3. 2. 3. 5. 5.]
按照行优先，展平
[4. 5. 5. 3. 9. 6. 3. 5. 4. 2. 2. 5.]


In [88]:
# 6.squeeze

import numpy as np

arr = np.arange(3).reshape(3,1)
print(arr.shape)
print(arr.squeeze().shape)
arr1 = np.arange(6).reshape(3,1,2,1)
print(arr1.shape)
print(arr1.squeeze().shape)

(3, 1)
(3,)
(3, 1, 2, 1)
(3, 2)


In [90]:
# 7.transpose

import numpy as np

arr2 = np.arange(24).reshape(2,3,4)
print(arr2.shape)
print(arr2.transpose(1,2,0).shape)

(2, 3, 4)
(3, 4, 2)


### 合并数组

In [93]:
# 1.append

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6,7])

c = np.append(a,b)
print(c)

[1 2 3 4 5 6 7]


In [102]:
import numpy as np

a = np.arange(2).reshape(1,2)
b = np.arange(4).reshape(2,2)
# 按行合并 -- 列数得相等
c = np.append(a,b,axis=0)
print("按行合并后的结果")
print(c)
print("合并后数据维度",c.shape)

d = np.arange(4).reshape(2,2)
e = np.arange(6).reshape(2,3)
# 按列合并 -- 行数得相等
f = np.append(d,e,axis=1)
print("按列合并后的结果")
print(f)
print("合并后数据维度",f.shape)

按行合并后的结果
[[0 1]
 [0 1]
 [2 3]]
合并后数据维度 (3, 2)
按列合并后的结果
[[0 1 0 1 2]
 [2 3 3 4 5]]
合并后数据维度 (2, 5)


In [122]:
# 2.concatenate

import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b),axis=0)
print(c)
d = np.concatenate((a,b.T),axis=1)
print(d)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [130]:
# 3.stack

import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array(([5,6],[7,8]))
print(np.stack((a,b),axis=0))
print("-----------")
print(np.stack((a,b),axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-----------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## 批量处理

In [14]:
import numpy as np

# 生成10000个形状为2x3的矩阵
data_train = np.random.randn(10000,2,3)
# 这是一个3维矩阵，第一个维度为样本数，后两个是数据形状
print(data_train.shape)
# 打乱这10000个数据
np.random.shuffle(data_train)
# 定义批量大小
batch_size = 100
print(len(data_train))
# 进行批处理
for i in range(0,len(data_train),batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])
    print("第{}批次，该批次的数据之和:{}".format(i,x_batch_sum))

(10000, 2, 3)
10000
第0批次，该批次的数据之和:3.2123163870887987
第100批次，该批次的数据之和:-21.734186059748126
第200批次，该批次的数据之和:16.947835527320915
第300批次，该批次的数据之和:39.51714320871406
第400批次，该批次的数据之和:-4.098958514300538
第500批次，该批次的数据之和:19.7088368401907
第600批次，该批次的数据之和:37.57612650083716
第700批次，该批次的数据之和:-10.098345898134944
第800批次，该批次的数据之和:30.44954664018074
第900批次，该批次的数据之和:23.916642246293577
第1000批次，该批次的数据之和:-40.82070138939913
第1100批次，该批次的数据之和:18.09256286820347
第1200批次，该批次的数据之和:-36.8950105433521
第1300批次，该批次的数据之和:-11.989159083772485
第1400批次，该批次的数据之和:7.065049422458907
第1500批次，该批次的数据之和:41.85876753127599
第1600批次，该批次的数据之和:2.050577867600296
第1700批次，该批次的数据之和:-4.208916265005761
第1800批次，该批次的数据之和:6.587406339720618
第1900批次，该批次的数据之和:-12.367854933040775
第2000批次，该批次的数据之和:-1.334878054032684
第2100批次，该批次的数据之和:31.559036787402636
第2200批次，该批次的数据之和:4.63810580902453
第2300批次，该批次的数据之和:-27.800979828446152
第2400批次，该批次的数据之和:12.29767534039894
第2500批次，该批次的数据之和:-3.381761946275436
第2600批次，该批次的数据之和:10.457089810006963
第2700批次，该批次的数据之和:21.008734884

## 通用函数

In [32]:
# 1.math 与 numpy 函数的性能比较

import time
import math
import numpy as np

x = [i * 0.001 for i in np.arange(1000000)] # 生成1000000个数，从0到1000000，步长0.001
print(len(x))
print(x[1])
start = time.time()
# 使用 enumerate 函数遍历列表 x。enumerate 会同时返回列表中每个元素的索引 i 和元素的值 t。
# 在这个循环中，i 是当前元素的索引，而 t 是当前元素的值
for i,t in enumerate(x):
    x[i] = math.sin(t)
print("math.sin:",time.time() - start)

x = [i * 0.001 for i in np.arange(1000000)]
x = np.array(x)
start = time.time()
np.sin(x)
print("numpy.sin:",time.time() - start)

1000000
0.001
math.sin: 0.09319210052490234
numpy.sin: 0.003838777542114258


In [41]:
# 2.循环与向量运算比较

import time
import numpy as np

x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)
# 使用循环计算点积
tic = time.process_time()
dot = 0
# x1，x2都是一维的直接对应的位置相乘
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print("dot = " + str(dot) + "\n for loop ----- Computation time = " + str(1000*(toc - tic)) + "ms")
# 使用 numpy 函数求点积
tic = time.process_time()
dot = 0
# x1，x2都是一维的直接对应的位置相乘
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " + str(dot) + "\n vector version ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 249606.2688148365
 for loop ----- Computation time = 187.34800000000007ms
dot = 249606.26881483174
 vector version ----- Computation time = 1.0639999999995098ms


## 广播机制

In [1]:
import numpy as np

A = np.arange(0,40,10).reshape(4,1)
B = np.arange(0,3)
print("A矩阵的形状:{},B矩阵的形状:{}".format(A.shape,B.shape))
C = A+B
print("C矩阵的形状:{}".format(C.shape))
print(C)

A矩阵的形状:(4, 1),B矩阵的形状:(3,)
C矩阵的形状:(4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
